services:
  php:
    build:
      context: ./php
    container_name: ${PROJECT_NAME}-php
    restart: always
    environment:
      TZ: ${APP_TIMEZONE}
    volumes:
      - ${PROJECT_PATH}:/var/www/html
    depends_on:
      - redis

  nginx:
    image: nginx:stable-alpine
    container_name: ${PROJECT_NAME}-nginx
    restart: always
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    volumes:
      - ${PROJECT_PATH}:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - php

  redis:
    image: redis:7-alpine
    container_name: ${PROJECT_NAME}-redis
    restart: always
    environment:
      TZ: ${APP_TIMEZONE}
